apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-ingress
spec:
  rules:
  - http:
      paths:
      - path: /login
        pathType: Prefix
        backend:
          serviceName: spring-login-service
          servicePort: 80
  - http:
      paths:
      - path: /profile
        pathType: Prefix
        backend:
          serviceName: spring-profile-service
          servicePort: 80
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: spring-chat-service
            servicePort: 80
