apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          resource:
            name: spring-chat-service
            port:
              number: 80
      - path: /login
        pathType: Exact
        backend:
          resource:
            name: spring-login-service
            port:
              number: 80
      - path: /profile
        pathType: Exact
        backend:
          resource:
            name: spring-profile-service
            port:
              number: 80
