apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-chat-deployment
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app: {{ .Values.app}}*/}}
{{/*    spec:*/}}
{{/*      containers:*/}}
{{/*        - resources:*/}}
{{/*            requests:*/}}
{{/*              cpu: 200m*/}}
{{/*        - name: {{ .Values.assoc_name}}*/}}
{{/*          image: {{ .Values.image}}*/}}
{{/*          ports:*/}}
{{/*            - containerPort: {{ .Values.cport}}*/}}
{{/*          env:*/}}
{{/*            - name: MYSQL_DB_HOST*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: spring-chat-config*/}}
{{/*                  key: mysql_db_host*/}}
{{/*            - name: MYSQL_DB_USER*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: spring-chat-config*/}}
{{/*                  key: mysql_db_user*/}}
{{/*            - name: MYSQL_DB_PASSWORD*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: spring-chat-config*/}}
{{/*                  key: mysql_db_password*/}}
{{/*            - name: MYSQL_DB_PORT*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: spring-chat-config*/}}
{{/*                  key: mysql_db_port*/}}
{{/*            - name: SPRING_REDIS_HOST*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: spring-chat-config*/}}
{{/*                  key: spring_redis_host*/}}
{{/*            - name: SPRING_REDIS_PASSWORD*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: spring-chat-config*/}}
{{/*                  key: spring_redis_password*/}}
{{/*            - name: SPRING_REDIS_PORT*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: spring-chat-config*/}}
{{/*                  key: spring_redis_port*/}}
{{/*            - name: RAW_TOPIC_MESSAGE*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: spring-chat-config*/}}
{{/*                  key: raw_topic_message*/}}
{{/*            - name: LIST_OF_PROFILE_ENDPOINTS*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  name: spring-chat-config*/}}
{{/*                  key: list_of_profile_endpoints*/}}

