apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-login-config
data:
  spring_redis_host: 'redis-service'
  spring_redis_password: 'SuperSecretRedisPassword'
  spring_redis_port: '6379'
  mysql_db_host: 'mysql-profile.default.svc.cluster.local'
  mysql_db_user: 'clouduser'
  mysql_db_password: '9Gabite9!'
  mysql_db_port: '3306'
  chat_endpoint: '35.237.129.65'
