apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profile-config
data:
  # update MySQL environment variables for the profile service
  mysql_db_host: 'mysql-profile.default.svc.cluster.local'
  mysql_db_user: 'clouduser'
  mysql_db_password: '9Gabite9'
  mysql_db_port: '3306'