apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-deployment
  labels:
    app: {{ .Values.app}}
spec:
  replicas: {{ .Values.num_rep}}
  selector:
    matchLabels:
      app: {{ .Values.app}}
  template:
    metadata:
      labels:
        app: {{ .Values.app}}
    spec:
      containers:
        - name: {{ .Values.assoc_name}}
          image: {{ .Values.image}}
          ports:
            - containerPort: {{ .Values.cport}}