apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app}}
  ports:
    - protocol: TCP
      port: {{ .Values.port}}
      targetPort: {{ .Values.cport}}
